name: Test

on:
  - pull_request
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - run: yarn install
      - run: yarn audit
      - run: yarn check:format
      - run: yarn test --coverage --ci -i
